version: '3.2'

services:
  database:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbsubscription
    networks:
      - system-network



networks:
  system-network:
    driver: bridge


